name = "wisdomshe-worker"
main = "worker.js"
compatibility_date = "2026-05-12"

[vars]
GH_OWNER = "RaymondLrb"
GH_REPO = "wisdomshe-site"
GH_TOKEN = "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";
GH_BRANCH = "main"
GH_DATA_PATH = "data/applications.json"
